import Navbar from "./Navbar";
import Head from "next/head";
import React, { ReactNode } from "react";

interface MyComponentProps {
  children: ReactNode;
  hero?: string;
}

const Layout: React.FC<MyComponentProps> = ({ children, hero }) => {
  return (
    <>
      <Head>
        <title>Potter&apos;s House Oregon City</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="has-background-light">{children}</main>
      <footer className="box has-background-black has-text-white">
        <p className="is-size-7 has-text-centered">
          &copy; {new Date().getFullYear()} Potter&apos;s House Oregon City |
          19146 Molalla Ave suite A, Oregon City, OR 97045
        </p>
      </footer>
    </>
  );
};

export default Layout;
